apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: order-service
  namespace: demo
  labels:
    app.kubernetes.io/name: order-service
    app.kubernetes.io/part-of: sre-demo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: order-service
