# Helm values for Grafana
# helm repo add grafana https://grafana.github.io/helm-charts
# helm install grafana grafana/grafana -n observability -f grafana-values.yaml

adminUser: admin
adminPassword: admin

service:
  type: ClusterIP
  port: 3000

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: VictoriaMetrics
        type: prometheus
        url: http://vmsingle-victoria-metrics.observability:8429
        access: proxy
        isDefault: true
        editable: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboardsConfigMaps:
  default: grafana-dashboards

persistence:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

podLabels:
  app.kubernetes.io/part-of: sre-demo

grafana.ini:
  server:
    root_url: "%(protocol)s://%(domain)s:%(http_port)s/"
  auth.anonymous:
    enabled: true
    org_role: Viewer
