apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: demo
  labels:
    app.kubernetes.io/name: postgres-exporter
    app.kubernetes.io/part-of: sre-demo
    app.kubernetes.io/component: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres-exporter
        app.kubernetes.io/part-of: sre-demo
        app.kubernetes.io/component: observability
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: demo-app
      containers:
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter:v0.16.0
          ports:
            - containerPort: 9187
              name: metrics
              protocol: TCP
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_URL
          args:
            - "--extend.query-path=/etc/postgres-exporter/queries.yaml"
          volumeMounts:
            - name: queries
              mountPath: /etc/postgres-exporter
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: queries
          configMap:
            name: pg-exporter-queries
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: demo
  labels:
    app.kubernetes.io/name: postgres-exporter
    app.kubernetes.io/part-of: sre-demo
spec:
  selector:
    app.kubernetes.io/name: postgres-exporter
  ports:
    - port: 9187
      targetPort: metrics
      protocol: TCP
      name: metrics
