apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: api-gateway
    newName: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/sre-demo/api-gateway
    newTag: REPLACE_WITH_TAG
  - name: order-service
    newName: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/sre-demo/order-service
    newTag: REPLACE_WITH_TAG
  - name: payment-service
    newName: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/sre-demo/payment-service
    newTag: REPLACE_WITH_TAG
  - name: mcp-server
    newName: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/sre-demo/mcp-server
    newTag: REPLACE_WITH_TAG
