apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: demo
  labels:
    app.kubernetes.io/part-of: sre-demo
type: Opaque
stringData:
  DATABASE_URL: "postgresql://sreadmin:REPLACE_WITH_PASSWORD@REPLACE_WITH_RDS_ENDPOINT:5432/sre_demo"
  PGHOST: "REPLACE_WITH_RDS_ENDPOINT"
  PGPORT: "5432"
  PGUSER: "sreadmin"
  PGPASSWORD: "REPLACE_WITH_PASSWORD"
  PGDATABASE: "sre_demo"
