apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: victoria-metrics
  namespace: observability
  labels:
    app.kubernetes.io/name: vmsingle
    app.kubernetes.io/part-of: sre-demo
spec:
  retentionPeriod: "24h"
  storage:
    storageClassName: gp2
    resources:
      requests:
        storage: 10Gi
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  extraArgs:
    dedup.minScrapeInterval: "15s"
